### ISSUE TITLE
Interfacing simulation output with Wavescalephant

### ISSUE THREAD

**Issue by epastorelli** [NeuralEnsemble/cobrawap#28]
We need to give simulation outputs in input to the pipeline.
In a first specific case, for instance, we can use TIF images obtained with simulation already convolved with Calcium function. Something similar to the TIF input coming from LENS data. I'm actually working on the production of such TIF images.

**Comment by gulpgiulia** [comment]
We propose to add blocks in stage1 to cover the path from numerical matrices (i.e. the output of spiking/meanfield sim) to tiff images to neo format

**Comment by rgutzen** [comment]
Rather than taking the detour via creating tiff images, the matrices with the simulated data can be loaded and entered into the pipeline directly.
For this you would need to create a `stage01_data_entry/scripts/curate_<simulationXY>.py` script from the available template script, and a config file `stage01_data_entry/configs/config_<simulationXY>.yaml` from the config template with the required metadata.
The Readme file of stage 1 also gives some more detailed instructions. 
If any infos are missing in the readme or the templates, that would also be great to know to improve them.

**Comment by epastorelli** [comment]
Indeed, I'm in parallel following also this second possibitiy (my first option), to directly use the matrices of simulated data.
